### ISSUE TITLE
Cannot visit UUIDTools::UUID

### ISSUE THREAD

**Issue by DanielBlanco** [jashmenn/activeuuid#2]
I believe below code must be added to your gem, because whenever I did something like post.comments.empty? I got a TypeError: Cannot visit UUIDTools::UUID.

``` ruby
module Arel
  module Visitors
    class DepthFirst < Arel::Visitors::Visitor
      def visit_UUIDTools_UUID(o)
        o.quoted_id
      end
    end
  end
end
```

**Comment by anujaware** [comment]
I am using activeuuid 0.6.0. I have upgraded my rails from 3.2.15 to 4.1.8 and I an facing same issue while updating object. Using activerecord_sqlserver_adapter gem 4.1.0 and ahoy_matey 1.1.1. Not able to figure out which gem causing this issue.
