### ISSUE TITLE
usage outside of Rails app

### ISSUE THREAD

**Issue by ak47** [jashmenn/activeuuid#57]
Is there some trick to making this work outside of Rails?

I've tried many permutations of load order and explicit calling "ActiveUUID::Patches.apply!".
All to no avail.

The uuid's keep coming out of MySQL looking like:
"\x9F\x03\xBCS@$M\x05\x91t\xE3c\xA3#\xDC\xE2"

And when I attempt to save into MySQL I get:
ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column 'guid' at row 1: INSERT INTO `things` (`guid`) VALUES (x'38306334366136352d646238622d343663332d613135322d363435646231643631613563')

What am I doing wrong here?

**Comment by ak47** [comment]
solved it, instead of relying on "require 'activeuuid'", instead do an explicit "ActiveUUID::Patches.apply!"

```ruby
require 'pry'
require 'rubygems'
require 'bundler/setup'

Bundler.require :default

require 'active_record'
require 'active_support/all'

ActiveRecord::Base.logger = Logger.new(File.dirname(__FILE__) + "/debug.log")
ActiveRecord::Base.configurations = YAML::load(File.read(File.dirname(__FILE__) + "/../config/database.yml"))
ActiveRecord::Base.establish_connection(:development)

# require 'activeuuid'
ActiveUUID::Patches.apply!

require File.join(File.expand_path('../', __FILE__), '../app/resources/v1/providers/provider')

binding.pry
puts 'o'
```

**Comment by hubert** [comment]
it would be great to update the readme with this info or make it so that the simple require works for both cases (rails and non-rails)
