### ISSUE TITLE
you can't redefine the primary key column 'id'.

### ISSUE THREAD

**Issue by JanC** [jashmenn/activeuuid#75]
Hi,
I'm getting this error when running `rake db:migrate`. My migration looks like this 

``` ruby
class CreateArticles < ActiveRecord::Migration
  def change
    create_table :articles do |t|
      t.uuid :uuid, :primary_key => false
      t.string :title
      t.text :text

      t.timestamps null: false
    end
    add_index :articles, :id
  end
end
```

and my model class is 

``` ruby
require 'activeuuid'

class Article < ActiveRecord::Base
  include ActiveUUID::UUID
end
```

If i don't set the `:id` as primary key, the db is migrated correctly but the id is not generated using UUID.

what did I do wrong ?

**Comment by JanC** [comment]
I forgot to add `:id => false` in 

``` ruby
create_table :articles, :id => false do |t|
...
```

**Comment by rcach001** [comment]
@JanC question - it's old I know. But what's the reason you initially had an ":id" in the migration? Did you add id:integer? And if so, ist that even necessary to add, or the values already have an id?

**Comment by JanC** [comment]
to be honest I don't remember what I ended up doing :)
